name: tryiak
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dropdown_search: ^6.0.2
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.3.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  gal: ^2.3.2
  
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  
  get_it: ^9.1.1
  go_router: ^17.0.0
  google_sign_in: ^7.1.1
  haptic_feedback: ^0.6.4+2
  internet_connection_checker_plus: ^2.7.2
  intl_phone_field: ^3.2.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^3.3.1
  page_transition: ^2.2.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2
  skeletonizer: ^2.0.1
  smooth_page_indicator: ^1.2.1
  toastification: ^3.0.3
  video_player: ^2.10.0

  permission_handler: ^11.3.0
  image_picker: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/l10n/
    - assets/tiryak_animation.mp4
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
